version: '3.8'

services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /nfs_shared/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      LOWER_CASE_TABLE_NAMES: 1
