version: '3.8'

services:
  django-app:
    container_name: django-app
    image: localhost:8443/django-app:latest
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             gunicorn mysite.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - "8000"
    volumes:
      - static_volume:/app/www_dir/static
    environment:
      - DEBUG=0
      - DB_HOST=192.168.127.131
      - DB_PORT=3306
      - DB_NAME=book_ex
      - DB_USER=zerock
      - DB_PASSWORD=zerock
      - CSRF_TRUSTED_ORIGINS=http://192.168.127.131:8000,http://localhost:8000 
  nginx:
    image: nginx:alpine
    container_name: nginx-django
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/static
    depends_on:
      - django-app

volumes:
  static_volume:
